name: Continuous Integration

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        id: yarn-cache

        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --pure-lockfile --prefer-offline

      - name: Check dependency licenses
        run: yarn check:licenses

      - name: Build packages
        run: yarn build

      - name: Lint code
        run: yarn lint

      - name: Run unit tests
        run: yarn test:ci

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v3

      - name: Create release PR or publish to npm
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/next'
        uses: changesets/action@master
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
